name: Run tests

on:
  push:
  pull_request:
    branches:
      - master
      - development

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Enforce Jira Issue Key in Pull Request Title
        uses: LajwardCo/enforce-pr-title-style-action@v1
        with:
          projectKey: DMS

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.22'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test DMS
        run: npm run test-dms
